version: '3.9'

services:
  db:
    container_name: postgres_payment
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: payment-system
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - payment
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_payment
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test.test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "3333:80"


networks:
  payment:
    name: payment_network
    driver: bridge

volumes:
  postgres_data: {}