version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment-system
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - payment

networks:
  payment:
    name: payment_network
    driver: bridge

